# Generated by Django 2.2.5 on 2020-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=20)),
                ('local', models.IntegerField(max_length=10)),
                ('sfs', models.IntegerField(max_length=10)),
                ('obs', models.IntegerField(max_length=10)),
                ('datatime', models.DateField()),
            ],
        ),
    ]
