# Generated by Django 2.2.5 on 2020-10-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20201015_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('CPU', models.IntegerField()),
                ('Mem', models.IntegerField()),
                ('Disk', models.IntegerField()),
                ('datatime', models.CharField(max_length=100)),
            ],
        ),
    ]
