# Generated by Django 2.2.5 on 2020-10-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_hostinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('cpu', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('cluster', models.CharField(max_length=100)),
                ('datatime', models.CharField(max_length=100)),
            ],
        ),
    ]
