# Generated by Django 2.1.7 on 2020-12-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=20)),
                ('dir', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
