# Generated by Django 2.1.7 on 2020-12-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='percent',
            name='project_unkown',
            field=models.IntegerField(default=None),
        ),
    ]
