# Generated by Django 2.1.7 on 2020-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_percent_project_unkown'),
    ]

    operations = [
        migrations.CreateModel(
            name='tongji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
