# Generated by Django 2.1.7 on 2020-12-31 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_tongji'),
    ]

    operations = [
        migrations.CreateModel(
            name='memory_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_id', models.CharField(max_length=20)),
                ('memory_total', models.IntegerField(default=0)),
                ('memory_used', models.IntegerField(default=0)),
                ('memory_free', models.IntegerField(default=0)),
                ('memory_share', models.IntegerField(default=0)),
                ('memory_bu_ca', models.IntegerField(default=0)),
                ('memory_available', models.IntegerField(default=0)),
                ('memory_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
