# Generated by Django 2.1.7 on 2021-01-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_cpu_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hostinfo',
        ),
        migrations.DeleteModel(
            name='info',
        ),
        migrations.DeleteModel(
            name='memory_info',
        ),
        migrations.DeleteModel(
            name='Percent',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
