# Generated by Django 2.1.7 on 2021-01-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20210104_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project1',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='project1',
            name='datatime',
        ),
    ]
