# Generated by Django 2.1.7 on 2021-01-05 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20210104_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=20)),
                ('dir_path', models.CharField(max_length=20)),
                ('dir_size', models.IntegerField(default=0)),
                ('dir_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('dir_unkown_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='get_obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_name', models.CharField(max_length=20)),
                ('obs_size', models.IntegerField(default=0)),
                ('obs_spending', models.IntegerField(default=0)),
                ('obs_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='get_obs_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_project_name', models.CharField(max_length=30)),
                ('obs_project_path', models.CharField(max_length=100)),
                ('obs_project_size', models.IntegerField(default=0)),
                ('obs_project_spending', models.IntegerField(default=0)),
                ('obs_project_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='get_sfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfs_name', models.CharField(max_length=20)),
                ('sfs_size', models.IntegerField(default=0)),
                ('sfs_spending', models.IntegerField(default=0)),
                ('sfs_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='get_sfs_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfs_project_name', models.CharField(max_length=30)),
                ('sfs_project_path', models.CharField(max_length=100)),
                ('sfs_project_size', models.IntegerField(default=0)),
                ('sfs_project_spending', models.IntegerField(default=0)),
                ('sfs_project_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='cpu_info',
        ),
        migrations.DeleteModel(
            name='Dir',
        ),
        migrations.DeleteModel(
            name='Project1',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='tongji',
        ),
    ]
