# Generated by Django 2.1.7 on 2021-01-05 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_auto_20210105_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_obs_dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_dir_name', models.CharField(max_length=20)),
                ('obs_dir_path', models.CharField(max_length=20)),
                ('obs_dir_size', models.IntegerField(default=0)),
                ('obs_dir_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('obs_dir_unkown_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='get_sfs_dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfs_dir_name', models.CharField(max_length=20)),
                ('sfs_dir_path', models.CharField(max_length=20)),
                ('sfs_dir_size', models.IntegerField(default=0)),
                ('sfs_dir_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sfs_dir_unkown_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='get_dir',
        ),
    ]
