# Generated by Django 2.1.7 on 2021-01-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_auto_20210105_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get_obs_dir',
            name='obs_dir_unkown_size',
        ),
        migrations.RemoveField(
            model_name='get_sfs_dir',
            name='sfs_dir_unkown_size',
        ),
    ]
