# Generated by Django 2.1.7 on 2021-01-06 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_auto_20210105_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_obs_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_obs_size', models.IntegerField(default=0)),
                ('dna_obs_spending', models.IntegerField(default=0)),
                ('rna_obs_size', models.IntegerField(default=0)),
                ('rna_obs_spending', models.IntegerField(default=0)),
                ('three_genome_obs_size', models.IntegerField(default=0)),
                ('three_genome_obs_spending', models.IntegerField(default=0)),
                ('meta_obs_size', models.IntegerField(default=0)),
                ('meta_obs_spending', models.IntegerField(default=0)),
                ('res_obs_size', models.IntegerField(default=0)),
                ('res_obs_spending', models.IntegerField(default=0)),
                ('med_obs_size', models.IntegerField(default=0)),
                ('med_obs_spending', models.IntegerField(default=0)),
                ('obs_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
