# Generated by Django 2.1.7 on 2021-01-06 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_get_obs_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_sfs_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_sfs_size', models.IntegerField(default=0)),
                ('dna_sfs_spending', models.IntegerField(default=0)),
                ('rna_sfs_size', models.IntegerField(default=0)),
                ('rna_sfs_spending', models.IntegerField(default=0)),
                ('three_genome_sfs_size', models.IntegerField(default=0)),
                ('three_genome_sfs_spending', models.IntegerField(default=0)),
                ('meta_sfs_size', models.IntegerField(default=0)),
                ('meta_sfs_spending', models.IntegerField(default=0)),
                ('res_sfs_size', models.IntegerField(default=0)),
                ('res_sfs_spending', models.IntegerField(default=0)),
                ('med_sfs_size', models.IntegerField(default=0)),
                ('med_sfs_spending', models.IntegerField(default=0)),
                ('sfs_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
