# Generated by Django 2.1.7 on 2021-01-11 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_get_sfs_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_obs_dir_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_obs_size', models.IntegerField(default=0)),
                ('dna_obs_sending', models.IntegerField(default=0)),
                ('rna_obs_size', models.IntegerField(default=0)),
                ('rna_obs_sending', models.IntegerField(default=0)),
                ('three_genome_obs_size', models.IntegerField(default=0)),
                ('three_genome_obs_spending', models.IntegerField(default=0)),
                ('meta_obs_size', models.IntegerField(default=0)),
                ('meta_obs_spending', models.IntegerField(default=0)),
                ('res_obs_size', models.IntegerField(default=0)),
                ('res_obs_spending', models.IntegerField(default=0)),
                ('med_obs_size', models.IntegerField(default=0)),
                ('med_obs_spending', models.IntegerField(default=0)),
                ('obs_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='get_obs_project_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_obs_project_size', models.IntegerField(default=0)),
                ('dna_obs_project_sending', models.IntegerField(default=0)),
                ('rna_obs_project_size', models.IntegerField(default=0)),
                ('rna_obs_project_sending', models.IntegerField(default=0)),
                ('three_genome_obs_project_size', models.IntegerField(default=0)),
                ('three_genome_obs_project_spending', models.IntegerField(default=0)),
                ('meta_obs_project_size', models.IntegerField(default=0)),
                ('meta_obs_project_spending', models.IntegerField(default=0)),
                ('res_obs_project_size', models.IntegerField(default=0)),
                ('res_obs_project_spending', models.IntegerField(default=0)),
                ('med_obs_project_size', models.IntegerField(default=0)),
                ('med_obs_project_spending', models.IntegerField(default=0)),
                ('obs_project_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='get_obs_dir',
        ),
        migrations.DeleteModel(
            name='get_obs_project',
        ),
    ]
