# Generated by Django 2.1.7 on 2021-01-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_auto_20210111_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='get_obs_dir_1',
        ),
        migrations.DeleteModel(
            name='get_obs_project_1',
        ),
    ]
