# Generated by Django 2.1.7 on 2021-01-13 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_auto_20210113_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_obs_dir_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_obs_dir_list', models.CharField(max_length=30)),
                ('dna_obs_dir_size', models.IntegerField(default=0)),
                ('dna_obs_dir_sending', models.IntegerField(default=0)),
                ('rna_obs_dir_list', models.CharField(max_length=30)),
                ('rna_obs_dir_size', models.IntegerField(default=0)),
                ('rna_obs_dir_sending', models.IntegerField(default=0)),
                ('three_genome_obs_dir_list', models.CharField(max_length=30)),
                ('three_genome_obs_dir_size', models.IntegerField(default=0)),
                ('three_genome_obs_dir_spending', models.IntegerField(default=0)),
                ('meta_obs_dir_list', models.CharField(max_length=30)),
                ('meta_obs_dir_size', models.IntegerField(default=0)),
                ('meta_obs_dir_spending', models.IntegerField(default=0)),
                ('res_obs_dir_list', models.CharField(max_length=30)),
                ('res_obs_dir_size', models.IntegerField(default=0)),
                ('res_obs_dir_spending', models.IntegerField(default=0)),
                ('med_obs_dir_list', models.CharField(max_length=30)),
                ('med_obs_dir_size', models.IntegerField(default=0)),
                ('med_obs_dir_spending', models.IntegerField(default=0)),
                ('obs_dir_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
