# Generated by Django 2.1.7 on 2021-01-13 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_get_obs_dir_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_obs_dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_dir_name', models.CharField(max_length=20)),
                ('obs_dir_path', models.CharField(max_length=20)),
                ('obs_dir_size', models.IntegerField(default=0)),
                ('obs_dir_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='get_obs_dir_2',
        ),
    ]
