# Generated by Django 2.1.7 on 2021-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_auto_20210113_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_obs_dir',
            name='obs_dir_spending',
            field=models.IntegerField(default=0),
        ),
    ]
