# Generated by Django 2.1.7 on 2021-01-20 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_auto_20210119_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_host', models.CharField(max_length=20)),
                ('cloud_host', models.CharField(max_length=20)),
                ('cpu_used', models.FloatField(default=0)),
                ('cpu_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
