# Generated by Django 2.1.7 on 2021-01-22 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_cpu_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_obs_project_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_project_name', models.CharField(max_length=30)),
                ('obs_project_path', models.CharField(max_length=100)),
                ('obs_project_size', models.IntegerField(default=0)),
                ('obs_project_spending', models.IntegerField(default=0)),
                ('obs_project_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
