# Generated by Django 2.1.7 on 2021-01-29 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0029_get_obs_project_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu_info2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('cpu_used', models.FloatField(default=0)),
                ('cpu_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
